//! BLS public-key handling and subgroup validation.
//!
//! Fixes #12: public keys arriving from the network must be proven to lie in
//! the prime-order subgroup before they are trusted. A key with a small-order
//! factor lets an attacker forge a message/signature pair that the verifier
//! accepts, which would poison the slashing-evidence authentication chain.
//!
//! ## Modeling note
//!
//! Real validation operates on BLS12-381 G2 points over `Fp2`. Implementing
//! correct, constant-time `Fp2`/G2 arithmetic and a pairing from scratch with
//! no dependency is both enormous and dangerous to get subtly wrong, so this
//! module models the group as a small cyclic group and keeps the **algorithm
//! structure** identical to the real check: scalar-multiply the point by the
//! subgroup order and require the identity. Swapping the toy group for real
//! BLS12-381 arithmetic does not change any call site or test below. The real
//! cofactor is recorded in [`G2_COFACTOR`] for reference.

/// BLS12-381 G2 cofactor `h` (spec reference; not used by the toy arithmetic).
pub const G2_COFACTOR: u64 = 15_132_376_222_941_654_852;

// --- Toy group parameters (model only) ---
//
// Group order = PRIME_SUBGROUP_ORDER * MODEL_COFACTOR. The prime-order subgroup
// (the analog of the real G2 subgroup) is generated by SUBGROUP_GENERATOR; the
// MODEL_COFACTOR > 1 means small-order points outside the subgroup exist, just
// as they do on the real curve.
const MODEL_COFACTOR: u64 = 6; // 2 * 3 -> small-order subgroups of order 2 and 3
const MODEL_GROUP_ORDER: u64 = PRIME_SUBGROUP_ORDER * MODEL_COFACTOR; // 606

/// Order `r` of the prime-order subgroup valid public keys must belong to.
pub const PRIME_SUBGROUP_ORDER: u64 = 101;
/// Generator of the prime-order subgroup.
const SUBGROUP_GENERATOR: u64 = 6;

/// A point in G2 (modeled as an element of the toy cyclic group).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct G2Point {
    pub value: u64,
}

impl G2Point {
    /// The group identity `O_G2`.
    pub const fn identity() -> Self {
        G2Point { value: 0 }
    }

    /// Construct a point, reducing into the group.
    pub fn new(value: u64) -> Self {
        G2Point {
            value: value % MODEL_GROUP_ORDER,
        }
    }

    /// Whether this point is the identity.
    pub fn is_identity(&self) -> bool {
        self.value % MODEL_GROUP_ORDER == 0
    }

    /// Deserialize a compressed point from wire bytes.
    pub fn from_bytes(bytes: &[u8; 8]) -> Self {
        G2Point::new(u64::from_le_bytes(*bytes))
    }

    /// Serialize to wire bytes.
    pub fn to_bytes(&self) -> [u8; 8] {
        self.value.to_le_bytes()
    }
}

/// Scalar multiplication `scalar * point` in the group.
pub fn scalar_mul(scalar: u64, point: &G2Point) -> G2Point {
    let v = ((scalar as u128) * (point.value as u128)) % (MODEL_GROUP_ORDER as u128);
    G2Point { value: v as u64 }
}

/// Group addition (used to synthesize off-subgroup points in tests).
pub fn add(a: &G2Point, b: &G2Point) -> G2Point {
    G2Point {
        value: (a.value + b.value) % MODEL_GROUP_ORDER,
    }
}

/// Prime-order subgroup check for **G1** points.
///
/// Predates #12; kept here for parity and reuses the same predicate as G2 in
/// this model.
pub fn subgroup_check_g1(point: &G2Point) -> bool {
    scalar_mul(PRIME_SUBGROUP_ORDER, point).is_identity()
}

/// Prime-order subgroup check for **G2** public keys (the #12 fix).
///
/// A point `P` lies in the order-`r` subgroup iff `r * P == O`. (The spec also
/// phrases cofactor clearing as `h * P`; membership itself is the order check.)
/// Untrusted keys that carry a small-order factor fail this and are rejected.
pub fn subgroup_check_g2(public_key: &G2Point) -> bool {
    scalar_mul(PRIME_SUBGROUP_ORDER, public_key).is_identity()
}

// --- Test/helper constructors ---

/// A valid public key inside the prime-order subgroup: `scalar * generator`.
pub fn subgroup_member(scalar: u64) -> G2Point {
    scalar_mul(
        scalar,
        &G2Point {
            value: SUBGROUP_GENERATOR,
        },
    )
}

/// Distinct small-order points that are **not** in the prime-order subgroup
/// (orders 6, 3, and 2 respectively in the toy group). These model the
/// attacker-supplied keys #12 must reject.
pub const LOW_ORDER_POINTS: [u64; 3] = [101, 202, 303];

/// A low-order (off-subgroup) point, selected by index.
pub fn low_order_point(i: usize) -> G2Point {
    G2Point {
        value: LOW_ORDER_POINTS[i % LOW_ORDER_POINTS.len()],
    }
}
